In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
crops = pd.read_csv('crop_production.csv')

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [4]:
crops.dropna(inplace=True)
import numpy as np
X1= crops['Area'].values
X2= crops['Production'].values
nx1= np.array(X1)
nx2= np.array(X2)
Y = crops['Season'].values

In [5]:
def Reduct_N_DigitValues(n,L):
    Ans=[]
    for i in range(len(L)):
        if(len(str(int(round(L[i]))))>(n-1)):
            Ans.append(int(str(int(round(L[i])))[:n]))
    return np.array(Ans)

In [6]:
nx2lists=[]
for i in range(1,6):
    nx2lists.append(Reduct_N_DigitValues(i,X2))

In [7]:
nx2lists

[array([2, 1, 3, ..., 1, 5, 8]),
 array([20, 32, 64, ..., 16, 59, 88]),
 array([200, 321, 641, ..., 463, 162, 597]),
 array([2000, 6510, 2061, ..., 2039, 1625, 5978]),
 array([65100, 64430, 67490, ..., 13337, 16250, 59789])]

In [8]:
nx1lists=[]
for i in range(1,6):
    nx1lists.append(Reduct_N_DigitValues(i,X1))

In [9]:
nx1lists

[array([1, 2, 1, ..., 3, 2, 1]),
 array([12, 10, 17, ..., 32, 27, 17]),
 array([125, 102, 176, ..., 324, 279, 175]),
 array([1254, 1816, 1254, ..., 1885, 1622, 2791]),
 array([18168, 18190, 18240, ..., 30227, 11493, 27915])]

In [10]:
def MinimizeLengthofLists(L1,L2,L3):
    Ans=[]
    L11= L1.tolist()
    L22= L2.tolist()
    Min = min(len(L11),len(L22))
    print("min = ",Min)
    if(Min==len(L11)):
        print('L11')
        for i in range(Min):
            Ans.append(L22[i])
        L22.clear()
        L22=Ans
    else:
        print('L22')
        for i in range(Min):
            Ans.append(L11[i])
        L11.clear()
        L11=Ans
    print(len(L11),len(L22),len(Ans),len(L3))
    Y1=[]
    for i in range(Min):
        Y1.append(L3[i])
    print(len(Y1))
    return np.array(L11),np.array(L22),np.array(Y1)
    
            

In [11]:
L=[]
for i in range(5):
    L1=[]
    Ans= MinimizeLengthofLists(nx1lists[i],nx2lists[i],Y)
    L1.append(Ans[0])
    L1.append(Ans[1])
    L1.append(Ans[2])
    L.append(L1)

min =  242361
L11
242361 242361 242361 242361
242361
min =  218943
L22
218943 218943 218943 242361
218943
min =  178438
L11
178438 178438 178438 242361
178438
min =  105643
L11
105643 105643 105643 242361
105643
min =  42367
L11
42367 42367 42367 242361
42367


In [12]:
NX = []
for i in L:
    NX.append(np.vstack((i[0],i[1])).T)
    

In [13]:
from sklearn.preprocessing import  StandardScaler
Scaler = StandardScaler()

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
NX[0]= Scaler.fit_transform(NX[0])
NX[0]

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.97525036, -0.53024364],
       [-0.56658216, -0.93977582],
       [-0.97525036, -0.12071146],
       ...,
       [-0.15791396, -0.93977582],
       [-0.56658216,  0.6983529 ],
       [-0.97525036,  1.92694944]])

In [16]:
TrainingTestData=[]
for i in range(5):
    NX[i]= Scaler.fit_transform(NX[i])
    TrainingTestData.append(train_test_split(NX[i],L[i][2],test_size=.4, random_state=42))

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by Stand

In [17]:
len(TrainingTestData)

5

In [17]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
RFclf = RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1)
from sklearn.neighbors import KNeighborsClassifier
knnclf = KNeighborsClassifier(3)
from sklearn import tree
DTclf = tree.DecisionTreeClassifier(max_depth=5)
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
GPCclf = GaussianProcessClassifier(1.0 * RBF(1.0))
from sklearn.neural_network import MLPClassifier
MLPclf = MLPClassifier(alpha=1)
from sklearn.naive_bayes import GaussianNB
Gussclf = GaussianNB()
from sklearn.ensemble import AdaBoostClassifier
Adbclf = AdaBoostClassifier()
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
QDAclf = QuadraticDiscriminantAnalysis()

In [18]:
PredictList=[]
ScoreList=[]
def GetScorePredictValue(L,clf):
    clf.fit(L[0],L[2])
    Predict = clf.predict(L[1])
    Score = clf.score(L[1],L[3])
#     accuracy = accuracy_score(L[3],Predict)
    return Score
    
    
# for i in TrainingTestData:
#     L=[]
#     S=[]
#     RFclf.fit(i[0],i[2])
#     knnclf.fit(i[0],i[2])
#     DTclf.fit(i[0],i[2])
#     GPCclf.fit(i[0],i[2])
#     MLPclf.fit(i[0],i[2])
#     Gussclf.fit(i[0],i[2])
#     Adbclf.fit(i[0],i[2])
#     QDAclf.fit(i[0],i[2])
#     L.append(RFclf.predict(i[1]))
#     L.append(knnclf.predict(i[1]))
#     L.append(DTclf.predict(i[1]))
#     L.append(GPCclf.predict(i[1]))
#     L.append(MLPclf.predict(i[1]))
#     L.append(Gussclf.predict(i[1]))
#     L.append(Adbclf.predict(i[1]))
#     L.append(QDAclf.predict(i[1]))
#     S.append()
#     PredictList.append(L)
    

In [20]:
# accuracyList=[]
# for i in range(5):
#     L=[]
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][0]))
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][1]))
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][2]))
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][3]))
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][4]))
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][5]))
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][6]))
#     L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][7]))
#     accuracyList.append(L)
RFPA=[]
for i in TrainingTestData:
    RFPA.append(GetScorePredictValue(i,RFclf))

In [21]:
RFPA

[(0.3962865542317809, 0.3962865542317809),
 (0.3912740642627144, 0.3912740642627144),
 (0.38356030038108047, 0.38356030038108047),
 (0.37065171091864263, 0.37065171091864263),
 (0.33651973800672685, 0.33651973800672685)]

In [22]:
AdaPA=[]
for i in TrainingTestData:
    AdaPA.append(GetScorePredictValue(i,Adbclf))

In [23]:
AdaPA

[(0.3962865542317809, 0.3962865542317809),
 (0.39131973783370255, 0.39131973783370255),
 (0.3842047747141896, 0.3842047747141896),
 (0.3702967485446543, 0.3702967485446543),
 (0.3345724907063197, 0.3345724907063197)]

In [26]:
KnnPA=[]
for i in TrainingTestData:
    KnnPA.append(GetScorePredictValue(i,knnclf))

In [27]:
KnnPA

[(0.29372324513899634, 0.29372324513899634),
 (0.32097102011920803, 0.32097102011920803),
 (0.3159325263393858, 0.3159325263393858),
 (0.3130531496994652, 0.3130531496994652),
 (0.30158730158730157, 0.30158730158730157)]

In [28]:
DTPA=[]
for i in TrainingTestData:
    DTPA.append(GetScorePredictValue(i,DTclf))

In [29]:
DTPA

[(0.3962865542317809, 0.3962865542317809),
 (0.3911827171207381, 0.3911827171207381),
 (0.38356030038108047, 0.38356030038108047),
 (0.3702257560698566, 0.3702257560698566),
 (0.33522157313978873, 0.33522157313978873)]

In [30]:
MLRPA=[]
for i in TrainingTestData:
    MLRPA.append(GetScorePredictValue(i,MLPclf))

In [32]:
MLRPA

[(0.38736396926092115, 0.38736396926092115),
 (0.39131973783370255, 0.39131973783370255),
 (0.3842327953373683, 0.3842327953373683),
 (0.3706753750769085, 0.3706753750769085),
 (0.33710981294624415, 0.33710981294624415)]

In [33]:
GussPA=[]
for i in TrainingTestData:
    GussPA.append(GetScorePredictValue(i,Gussclf))

In [34]:
GussPA

[0.38736396926092115,
 0.39131973783370255,
 0.3842327953373683,
 0.3706753750769085,
 0.3364017230188234]

In [35]:
QdaPA=[]
for i in TrainingTestData:
    QdaPA.append(GetScorePredictValue(i,QDAclf))

In [36]:
QdaPA

[0.38736396926092115,
 0.39131973783370255,
 0.3842327953373683,
 0.3706753750769085,
 0.3364017230188234]

In [ ]:
GPCPA=[]
for i in TrainingTestData:
    GPCPA.append(GetScorePredictValue(i,GPCclf))

In [1]:
from sklearn.svm import  SVC
SVCgamma = SVC(gamma=2,C=1)

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
SVClinear= SVC(kernel="linear", C=0.025)

In [19]:
SVCgammaPA=[]
for i in TrainingTestData:
    SVCgammaPA.append(GetScorePredictValue(i,SVCgamma))

KeyboardInterrupt: 

In [ ]:
SVLingammaPA=[]
for i in TrainingTestData:
    SVLingammaPA.append(GetScorePredictValue(i,SVClinear))