In [68]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
crops = pd.read_csv('crop_production.csv')

In [69]:
crops.dropna(inplace=True)
import numpy as np
X1= crops['Area'].values
X2= crops['Production'].values
nx1= np.array(X1)
nx2= np.array(X2)
Y = crops['Season'].values

In [70]:
def Reduct_N_DigitValues(n,L):
    Ans=[]
    for i in range(len(L)):
        if(len(str(int(round(L[i]))))>(n-1)):
            Ans.append(int(str(int(round(L[i])))[:n]))
    return np.array(Ans)

In [71]:
X1

array([1.25400e+03, 2.00000e+00, 1.02000e+02, ..., 3.24000e+02,
       2.79151e+05, 1.75000e+02])

In [72]:
nx12digit= Reduct_N_DigitValues(2,X1)

In [73]:
nx12digit

array([12, 10, 17, ..., 32, 27, 17])

In [74]:
nx13digit = Reduct_N_DigitValues(3,X1)

In [75]:
nx13digit

array([125, 102, 176, ..., 324, 279, 175])

In [76]:
nx14digit = Reduct_N_DigitValues(4,X1)

In [77]:
nx14digit

array([1254, 1816, 1254, ..., 1885, 1622, 2791])

In [78]:
nx15digit = Reduct_N_DigitValues(5,X1)

In [79]:
nx15digit

array([18168, 18190, 18240, ..., 30227, 11493, 27915])

In [80]:
nx11digit = Reduct_N_DigitValues(1,X1)

In [81]:
len(nx11digit)

242361

In [82]:
nx21digit= Reduct_N_DigitValues(1,X2)

In [83]:
len(nx21digit)

242361

In [84]:
X2

array([2.00000e+03, 1.00000e+00, 3.21000e+02, ..., 1.62500e+04,
       5.97899e+05, 8.80000e+01])

In [87]:
nx2lists=[]
for i in range(1,6):
    nx2lists.append(Reduct_N_DigitValues(i,X2))

In [88]:
nx2lists

[array([2, 1, 3, ..., 1, 5, 8]),
 array([20, 32, 64, ..., 16, 59, 88]),
 array([200, 321, 641, ..., 463, 162, 597]),
 array([2000, 6510, 2061, ..., 2039, 1625, 5978]),
 array([65100, 64430, 67490, ..., 13337, 16250, 59789])]

In [89]:
nx1lists=[]
for i in range(1,6):
    nx1lists.append(Reduct_N_DigitValues(i,X1))

In [90]:
nx1lists

[array([1, 2, 1, ..., 3, 2, 1]),
 array([12, 10, 17, ..., 32, 27, 17]),
 array([125, 102, 176, ..., 324, 279, 175]),
 array([1254, 1816, 1254, ..., 1885, 1622, 2791]),
 array([18168, 18190, 18240, ..., 30227, 11493, 27915])]

In [124]:
def MinimizeLengthofLists(L1,L2,L3):
    Ans=[]
    L11= L1.tolist()
    L22= L2.tolist()
    Min = min(len(L11),len(L22))
    print("min = ",Min)
    if(Min==len(L11)):
        print('L11')
        for i in range(Min):
            Ans.append(L22[i])
        L22.clear()
        L22=Ans
    else:
        print('L22')
        for i in range(Min):
            Ans.append(L11[i])
        L11.clear()
        L11=Ans
    print(len(L11),len(L22),len(Ans),len(L3))
    Y1=[]
    for i in range(Min):
        Y1.append(L3[i])
    print(len(Y1))
    return np.array(L11),np.array(L22),np.array(Y1)
    
            

In [125]:
ANS = MinimizeLengthofLists(nx1lists[1],nx2lists[1],Y)
# for i in ANS:
#     print(i,len(i))

min =  218943
L22
218943 218943 218943 242361
218943


In [126]:
L=[]
for i in range(5):
    L1=[]
    Ans= MinimizeLengthofLists(nx1lists[i],nx2lists[i],Y)
    L1.append(Ans[0])
    L1.append(Ans[1])
    L1.append(Ans[2])
    L.append(L1)
    

min =  242361
L11
242361 242361 242361 242361
242361
min =  218943
L22
218943 218943 218943 242361
218943
min =  178438
L11
178438 178438 178438 242361
178438
min =  105643
L11
105643 105643 105643 242361
105643
min =  42367
L11
42367 42367 42367 242361
42367


In [127]:
len(L)

5

In [131]:
NX = []
for i in L:
    NX.append(np.vstack((i[0],i[1])).T)
    

In [132]:
from sklearn.preprocessing import  StandardScaler
Scaler = StandardScaler()

In [139]:
NX[4]

array([[18168, 65100],
       [18190, 64430],
       [18240, 67490],
       ...,
       [30227, 89449],
       [11493, 34424],
       [27915, 11318]])

In [140]:
from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test =  train_test_split(nx,ny,test_size=0.25)
TrainingTestData=[]
for i in range(5):
    TrainingTestData.append(train_test_split(NX[i],L[i][2],test_size=0.25))
    

In [148]:
len(TrainingTestData)

5

In [142]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
RFclf = RandomForestClassifier(n_estimators=10)
from sklearn.svm import SVC
SVMclassifier = SVC(kernel='linear')
from sklearn.neighbors import KNeighborsClassifier
knnclf = KNeighborsClassifier()
from sklearn import tree
DTclf = tree.DecisionTreeClassifier()

In [ ]:
PredictList=[]
for i in TrainingTestData:
    L=[]
    RFclf.fit(i[0],i[2])
    knnclf.fit(i[0],i[2])
    DTclf.fit(i[0],i[2])
    SVMclassifier.fit(i[0],i[2])
    L.append(RFclf.predict(i[1]))
    L.append(knnclf.predict(i[1]))
    L.append(DTclf.predict(i[1]))
    L.append(SVMclassifier.predict(i[1]))
    PredictList.append(L)
    

In [149]:
accuracyList=[]
for i in range(5):
    L=[]
    L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][0]))
    L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][1]))
    L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][2]))
    L.append(accuracy_score(TrainingTestData[i][3],PredictList[i][3]))
    accuracyList.append(L)
    


In [150]:
for i in accuracyList:
    print(i)

[0.39685761911835093, 0.3260220164710931, 0.39685761911835093]
[0.35709587839812923, 0.3358484361297866, 0.3653536977491961]
[0.298453261600538, 0.33230217440035864, 0.2933422999327505]
[0.3036992162356594, 0.3214569686872894, 0.2861307788421491]
[0.30117069486404835, 0.3137273413897281, 0.2809667673716012]
