In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
crops = pd.read_csv('crop_production.csv')

In [2]:
crops.shape

(246091, 7)

In [3]:
crops.head()

State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    

                  Crop    Area  Production  
0             Arecanut  1254.0      2000.0  
1  Other Kharif pulses     2.0         1.0  
2                 Rice   102.0       321.0  
3               Banana   176.0       641.0  
4            Cashewnut   720.0       165.0

In [5]:
Seasoncount=pd.value_counts(crops['Season'])

In [6]:
print(len(Seasoncount),type(Seasoncount))

6 <class 'pandas.core.series.Series'>


In [7]:
for i in Seasoncount:
    print(i)

95951
66987
57305
14841
6058
4949


In [8]:
Cropcount=pd.value_counts(crops['Crop'])

In [42]:
Cropcount[0]

15104

In [14]:
DistrictNameCount = pd.value_counts(crops['District_Name'])

In [15]:
DistrictNameCount

BIJAPUR                     945
TUMKUR                      936
BELGAUM                     925
HASSAN                      895
BELLARY                     887
DAVANGERE                   886
AURANGABAD                  879
HAVERI                      870
CHAMARAJANAGAR              844
CHITRADURGA                 840
GULBARGA                    833
MYSORE                      832
KURNOOL                     828
DHARWAD                     825
SHIMOGA                     825
KADAPA                      824
CHIKMAGALUR                 820
BILASPUR                    815
VISAKHAPATANAM              812
PRAKASAM                    808
BANGALORE RURAL             794
CHITTOOR                    789
ANANTAPUR                   788
BIDAR                       781
MANDYA                      780
EAST GODAVARI               765
GADAG                       755
VIZIANAGARAM                741
BAGALKOT                    733
MEDAK                       714
                           ... 
DEOGHAR 

In [16]:
IndianstateNameCount = pd.value_counts(crops['State_Name'])

In [17]:
 IndianstateNameCount

Uttar Pradesh                  33306
Madhya Pradesh                 22943
Karnataka                      21122
Bihar                          18885
Assam                          14628
Odisha                         13575
Tamil Nadu                     13547
Maharashtra                    12628
Rajasthan                      12514
Chhattisgarh                   10709
Andhra Pradesh                  9628
West Bengal                     9613
Gujarat                         8436
Haryana                         5875
Telangana                       5649
Uttarakhand                     4896
Kerala                          4261
Nagaland                        3906
Punjab                          3173
Meghalaya                       2867
Arunachal Pradesh               2546
Himachal Pradesh                2494
Jammu and Kashmir               1634
Tripura                         1412
Manipur                         1267
Jharkhand                       1266
Mizoram                          957
P

In [18]:
len(IndianstateNameCount)

33

In [19]:
pd.unique(IndianstateNameCount)

array([33306, 22943, 21122, 18885, 14628, 13575, 13547, 12628, 12514,
       10709,  9628,  9613,  8436,  5875,  5649,  4896,  4261,  3906,
        3173,  2867,  2546,  2494,  1634,  1412,  1267,  1266,   957,
         876,   714,   263,   208,   203,    90])

In [20]:
pd.unique(Cropcount)

array([15104, 13947, 10318,  9850,  9046,  8834,  7921,  7899,  7592,
        7578,  7361,  7065,  7012,  6931,  6489,  5571,  5427,  4652,
        4524,  4518,  4405,  4224,  4202,  4199,  4198,  4145,  3902,
        3659,  3376,  3369,  3289,  3212,  3209,  3180,  3008,  2698,
        2395,  2070,  1985,  1787,  1586,  1577,  1453,  1360,  1335,
        1295,  1081,   934,   878,   633,   628,   587,   483,   479,
         449,   427,   426,   410,   386,   381,   368,   301,   297,
         271,   266,   247,   241,   236,   205,   188,   167,   129,
         126,   122,   118,   112,    93,    92,    87,    85,    84,
          82,    70,    69,    66,    62,    61,    58,    48,    44,
          39,    38,    36,    35,    31,    29,    28,    21,    20,
          18,    16,    12,    11,    10,     9,     8,     6,     4,
           1])

In [21]:
pd.unique(DistrictNameCount).shape

(415,)

In [23]:
crops.dropna(inplace=True)

In [24]:
crops.shape

(242361, 7)

In [35]:
crops['Area']

0           1254.0
1              2.0
2            102.0
3            176.0
4            720.0
5          18168.0
6             36.0
7              1.0
8              5.0
9             40.0
10          1254.0
11             2.0
12            83.0
13           719.0
14         18190.0
15            46.0
16             1.0
17            11.0
18           189.2
19          1258.0
20           213.0
21            63.0
22           719.0
23         18240.0
24           413.0
25            47.3
26             5.0
27            52.0
28          1261.0
29           266.0
            ...   
246061        49.0
246062       159.0
246063       181.0
246064        16.0
246065       204.0
246066        79.0
246067       171.0
246068        18.0
246069        46.0
246070     11493.0
246071       671.0
246072       198.0
246073        30.0
246074       660.0
246075       146.0
246076       160.0
246077        31.0
246078        64.0
246079        12.0
246080       477.0
246081      1885.0
246082      

In [65]:
import numpy as np
X1= crops['Area'].values
X2= crops['Production'].values
nx1= np.array(X1)
nx2= np.array(X2)
Y= crops['Season']
X= crops.iloc[:,5:].values

In [94]:
L1=[]
L2=[]
for i in range(len(nx1)):
    if(len(str(int(round(nx1[i]))))>1):
        L1.append(int(str(int(round(nx1[i])))[:2]))
#         print(int(str(int(round(nx1[i])))[:2]))
    else:
        L1.append(int(round(nx1[i])))
#         print(int(round(nx1[i])))
for i in range(len(nx2)):
    if(len(str(int(round(nx2[i]))))>1):
        L2.append(int(str(int(round(nx2[i])))[:2]))
#         print(int(str(int(round(nx1[i])))[:2]))
    else:
        L2.append(int(round(nx2[i])))
#         print(int(round(nx1[i])))
nx1= np.array(L1)
nx2= np.array(L2)

In [97]:
len(nx2)

242361

In [98]:
nx= np.vstack((nx1,nx2)).T

In [99]:
nx

array([[12, 20],
       [ 2,  1],
       [10, 32],
       ...,
       [32, 16],
       [27, 59],
       [17, 88]])

In [102]:
nx

array([[12, 20],
       [ 2,  1],
       [10, 32],
       ...,
       [32, 16],
       [27, 59],
       [17, 88]])

In [103]:
X

array([[1.25400e+03, 2.00000e+03],
       [2.00000e+00, 1.00000e+00],
       [1.02000e+02, 3.21000e+02],
       ...,
       [3.24000e+02, 1.62500e+04],
       [2.79151e+05, 5.97899e+05],
       [1.75000e+02, 8.80000e+01]])

In [104]:
from sklearn.preprocessing import  StandardScaler
Scaler = StandardScaler()

In [105]:
nx11= Scaler.fit(nx)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [106]:
nx11

StandardScaler(copy=True, with_mean=True, with_std=True)

In [107]:
Scaler.mean_

array([34.47527861, 33.61868452])

In [108]:
PARAM=Scaler.get_params

In [109]:
PARAM

<bound method BaseEstimator.get_params of StandardScaler(copy=True, with_mean=True, with_std=True)>

In [111]:
Scaler.transform(nx)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.89034736, -0.53954986],
       [-1.28649256, -1.29229857],
       [-0.9695764 , -0.06412962],
       ...,
       [-0.09805697, -0.69802327],
       [-0.29612957,  1.00556592],
       [-0.69227477,  2.15449817]])

In [120]:
from sklearn.neighbors import KNeighborsClassifier
kclf = KNeighborsClassifier()


In [121]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =  train_test_split(nx,Y,test_size=0.25)

In [123]:
X_train = Scaler.fit_transform(x_train)
x_test = Scaler.transform(x_test)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [124]:
kclf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [125]:
y_pred = kclf.predict(x_test)

In [126]:
from sklearn.metrics import accuracy_score

In [127]:
accuracy_score(y_test,y_predict)

0.3284811275601987

In [128]:
from sklearn.svm import SVC


In [129]:
classifier = SVC(kernel='linear')

In [ ]:
classifier.fit(X_train, y_train)